### ISSUE TITLE
Bad optimization

### ISSUE THREAD

**Issue by Dino-Kupinic** [d-hain/minesweeper_rs#1]
Hello your program takes quite alot of resources for being 2D application that listens for clicks.
20% cpu with 30% gpu usage on idle. 

![image](https://user-images.githubusercontent.com/87943435/219976591-372baa89-6143-45f4-8ffb-7bfa38e31bdf.png)

Everything else is very good.
Please fix. Thank you

**Comment by s-prechtl** [comment]
This is due to the graphics library we used, not a fault caused by our insane programming skills
